/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jokenpo;
import javax.swing.*;
/**
 *
 * @author guilherme
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    
    
    public static int randInt(int min, int max){
        java.util.Random rand = new java.util.Random();
        int randomNum = rand.nextInt((max - min) + 1) + min;
        return randomNum;
    } /* A variável x recebe um numero entre 0 e 2 */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pd = new javax.swing.JRadioButton();
        pp = new javax.swing.JRadioButton();
        ts = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedra, Papel ou Tesoura?");

        group.add(pd);
        pd.setText("Pedra");
        pd.addActionListener(this::pdActionPerformed);

        group.add(pp);
        pp.setText("Papel");

        group.add(ts);
        ts.setText("Tesoura");

        jButton1.setText("Jogar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pd)
                            .addComponent(pp)
                            .addComponent(ts)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pd)
                .addGap(18, 18, 18)
                .addComponent(pp)
                .addGap(18, 18, 18)
                .addComponent(ts)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int tp = randInt(1, 3); // 1: Pedra; 2: Papel; 3: Tesoura
        
        if(pd.isSelected()){ // caso o usuario escolha Pedra
            switch(tp){
                case 1:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Pedra! É um Empate!");
                break;
                
                case 2:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Papel\n É uma Derrota!");
                break;
                
                case 3:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Tesoura\n É uma Vitória!");
                break;
            }
        } else if(pp.isSelected()){ // caso o usuario escolha Papel
            switch(tp){
                case 1:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Pedra! É uma Vitória!");
                break;
                
                case 2:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Papel\n É um Empate!");
                break;
                
                case 3:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Tesoura\n É uma Derrota!");
                break;
            }
        } else if(ts.isSelected()){ // caso o usuario escolha Tesoura
            switch(tp){
                case 1:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Pedra! É uma Derrota!");
                break;
                
                case 2:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Papel\n É uma Vitória!");
                break;
                
                case 3:
                    JOptionPane.showMessageDialog(null, "A máquina colocou Tesoura\n É uma Empate!");
                break;
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup group;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton pd;
    private javax.swing.JRadioButton pp;
    private javax.swing.JRadioButton ts;
    // End of variables declaration//GEN-END:variables
}
