/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora_de_pesos;
import javax.swing.*;
/**
 *
 * @author guilherme
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        botao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mercurio = new javax.swing.JRadioButton();
        venus = new javax.swing.JRadioButton();
        marte = new javax.swing.JRadioButton();
        jupiter = new javax.swing.JRadioButton();
        saturno = new javax.swing.JRadioButton();
        urano = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel1.setText("Peso na Terra (kg):");
        jLabel1.setToolTipText("");

        peso.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        botao.setText("Calcular peso");
        botao.addActionListener(this::botaoActionPerformed);

        jLabel2.setText("Selecione o Planeta:");

        grupo.add(mercurio);
        mercurio.setText("Mecúrio");
        mercurio.setToolTipText("");
        mercurio.addActionListener(this::mercurioActionPerformed);

        grupo.add(venus);
        venus.setText("Vênus");
        venus.addActionListener(this::venusActionPerformed);

        grupo.add(marte);
        marte.setText("Marte");

        grupo.add(jupiter);
        jupiter.setText("Júpiter");

        grupo.add(saturno);
        saturno.setText("Saturno");

        grupo.add(urano);
        urano.setText("Urano");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mercurio)
                            .addComponent(venus))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marte)
                            .addComponent(jupiter))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urano)
                            .addComponent(saturno))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mercurio)
                    .addComponent(marte)
                    .addComponent(saturno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venus)
                    .addComponent(jupiter)
                    .addComponent(urano))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mercurioActionPerformed

    private void venusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venusActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:
        double ps = Double.parseDouble(peso.getText());
        
        if(mercurio.isSelected()){
            double res = ps / 10 * 0.37;
            JOptionPane.showMessageDialog(null, "Você pesa " + res + "kg em Mercúrio");
        } else if(venus.isSelected()){
            double res = ps / 10 * 0.88;
            JOptionPane.showMessageDialog(null, "Você pesa " + res + "kg em Vênus");
        } else if(marte.isSelected()){
            double res = ps / 10 * 0.38;
            JOptionPane.showMessageDialog(null, "Você pesa " + res + "kg em Marte");
        } else if(jupiter.isSelected()){
            double res = ps / 10 * 2.64;
            JOptionPane.showMessageDialog(null, "Você pesa " + res + "kg em Júpiter");
        } else if(saturno.isSelected()){
            double res = ps / 10 * 1.15;
            JOptionPane.showMessageDialog(null, "Você pesa " + res + "kg em Saturno");
        } else if(urano.isSelected()){
            double res = ps / 10 * 1.17;
            JOptionPane.showMessageDialog(null, "Você pesa " + res + "kg em Urano");
        }
    }//GEN-LAST:event_botaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jupiter;
    private javax.swing.JRadioButton marte;
    private javax.swing.JRadioButton mercurio;
    private javax.swing.JTextField peso;
    private javax.swing.JRadioButton saturno;
    private javax.swing.JRadioButton urano;
    private javax.swing.JRadioButton venus;
    // End of variables declaration//GEN-END:variables
}
